---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret1
  namespace: test-ns1
spec:
  encryptedData:
    password: AgBn4nWmYxrt4scf0947QR03kzTlSzJhtjomADgJO00lqoPR78k1KoH0aT6tMr3vDXzl3qD1b62dRAa+DXsZKSMGy7l3v6E32B8nMSGzq6/D1xjIORyImyeHmNi2gu4RxfNYFBTBBLwTvBSXTO7JRC8xj0jvqUsRKnTbhbXAM/RUZW9P+segLam+wzX/VH9nw7x80SIzzwvqKNXqKGxOz0I+kPkO9lNh2M91BvjGPLA8qif7rQsPQnMa2tiZmaoq/uD1hhr9lxVwHTKZMw7VOGWYCZ0GDQxpyxkAkKcrQuxNeGbuJ2MYzE12GLvjm7RsMGCKSAktWRNIrtN/0KXQGuqPGtLJyE7MyZwzLXwcp+VVFtFkvNZgaI3PCahteilB4QTaLPKx0YdUtzz9gFKdX/nkvEppklfyXddkTgILa6acCJK8FfCnmmspqZmWQH33gSLgxI5GGC0Gnshqo5mknEctvGJFr3WOH1Tn+Tcep3CCw1oBBUHjhUh8eBjMBNz+fB/YjBD8PshdrPtsKEht+LORRULcTzkKN5xyYakLXZ55JyZPsJeKdsOApgXp6JjXdQHD1jFhcSye3Nddt9bodtkpwm94NVaVN6o0oeTYscGUwdp+0Ucu8et82ldRXaX6pOKE3htvgDgdXrrs6+QvIsXOc9VIV7U2qKuTGgg1vnXsvnK+DuX+9HHlIi9p4C0YbWLvQmP/xMFOw//m3w==
    username: AgADdXDs0NRNMXRKojjA5fMWgekKidmk3qDzpR5IaTZr1jkQc7I/04YhhhqwI5pNXbJBrDP56DZo5cN2rEn6T0vCs4wjLSv3uuwMocSkWzGOLgS8Tg9BAs2p/JeMadImMf71LqBMNMbvHe4OrYSTZu/dLcA8JFqCqyQRDZZ43GPlogUjU6AsFJZ3XuH85Jp11nYdVovKcu9MPGWX5NieZp5mDpD1VS5FHgPuTzBrF13QrF+K8IoMLNitTfj7kiq2j3/sD+gNV9IVbZ4GLGi+jAh7RvtWpem1/d0oW/QJ2n0QIXMChgkdTerUFeCcLTQut0E08G/qpdxsero0IhZzSSt7skbXWiipQ48krXJEO7gKNVFzHYaxsw847aIse8+Ph2bDPP/P537aQWxK+y2zL1kZ+UU7tu9rJgx78I4fWNmRvqbJXLwHNpPtA6JXONRNEwWIcsHjIyc0WkR0ADKqpM3gEyq4JQ214W6L+G2P9gGGf6TJVA7G3Or5HNUE2dgg9FfMesTkKb+akUX+odPvneYMHuSGIQBKK/MkMJcGSY3wtXbXPb26vP8bn3+evYPPDGeWPV9B3PSL3pbpffhio1NusqAdJ0BrIozr57O+CWvMEM9AaLqdpc+PLK+2ODMS+diBKwyt+ePurxjR+E1uaKMOYOT1T+a3dybWNEmbi15xHIRtiUmZSEuU05iNFmAn/mbfGo3fTA==
  template:
    metadata:
      creationTimestamp: null
      name: secret1
      namespace: test-ns1
    type: Opaque
