---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret2
  namespace: test-ns1
spec:
  encryptedData:
    api-key: AgAYF+gcdl7y1E6OR5wN+6oFLlyTwNbHBAR6VI9BX4U6had7kzaTEnpqb76GBPnRBzJTbbBQSUeZaFUr5uiqG6p2qTGpYrvYOUy8yZyVMYCEIp0NaqTk74PT8yUXHNNnrn0GLwRhYewYEoNA7eon48rPE1a2JsBZNr4hk5Qxqgcv+O/4XHGSAAXqqT4VamnbmeP2KiPzOfu5GxEEvDEAWEMyak4zw1SmpNicZvNsL8agp2U9lIDKZmHR1dxwInS679Z43SYFReVohoMAjSHsoBC264q/tL+BYoAsJ6ENRibPvzrCUvC0OtPKSODCG5+zfyL0UwP9ob2wzQZ2W6KKASPavLWpKCDmMruoIWzkMkMmgaINz8erUJZbzEdGGdCVfMwkdc5wG4mciVSVosI1VJTcfm0/+PFHVk6+DyaYr3ArXoBKbv2nX2tJfEHCemvw1mX2RKLtfTNbLoDaiEgmG8dnJ0tYkwnWtbiWgMWkCr52mSEeHiizTs+OThFzV4lGX5nnm4oGr6hMdlyhZygRgDPt0VStMcon85l2KsqnesIjK2Mljy9FxlYqPPdCxM0X1cwVY+UXTwcDaHSGeWDrTzaXgdUmjKef4yUx+aN3TdydaYCRgX8E28EY54k16gQs5HzqRH1MKH7YV66lgxfDB8bUssfjITQiEVREWcw6Y16uSVqhgVhe26wDuvsUWF+AcbTt/7KKX4Jz9RhuK9A=
  template:
    metadata:
      creationTimestamp: null
      name: secret2
      namespace: test-ns1
    type: Opaque
