apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysql-secret
  namespace: default
spec:
  encryptedData:
    MYSQL_DATABASE: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEq/MEWZhGUfuLQM...
    MYSQL_PASSWORD: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEq/MEWZhGUfuLQM...
    MYSQL_ROOT_PASSWORD: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEq/MEWZhGUfuLQM...
    MYSQL_USER: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEq/MEWZhGUfuLQM...
  template:
    metadata:
      name: mysql-secret
    type: Opaque