---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: test-sealed-secrets
spec:
  encryptedData:
    password: AgClem3nRvuRN2sgELtIcfAGDRtsPDLaPGT7Hn/LeY21UyXLL70SA11032Aj9OS9zcfQ+Ig/PEP6b4+9ilgEy5l84zOivms4PcOiohqVLEEWcUBJcX6wto6A1HEjqpGKOG31WtVsi5ELIwfdPO0RFA1s0HQ3t8A5MWrDmI91Ws6PVko3jvS3dM37JwaJTp61tTUq0As6Z7MTF0Say8J4sEvujlgjiobW+sbuDxaMWOsPf9cyNvRWCOJAdqLNmafoVSAMJG9oWdC7N8/Ssu3iDdl1tauQN8y/BQuoR5tP0Ol06IGSr3EgTsP29zNqXt2QiTkY22Fps9NbIdl0jwpkUBiCl9g/uO1D4l5DAbHoie+o0YjDlPaUEeF0OSDUV6vw4S/lvDK1aGSVC+nYRBqsR625NvsdYfRJq9MY+KvL2WMdmV8u9Lh5MwCDM60/Jw1CdK7zHhys7kJUpbDw9BtpsM/GZMk3TiOsKmMoQ2vkTeMzrkU/bUQLjBfT1MWhB9oiuJbcxgkO2Ur2K5gzd9iPrErXPdWwGYPLi2EsFuCltfnTsB+q9R/7BVrOvhwpE5ereJ81jzCcbrqaMvEs13xORY3GIknnivS2fBPscA8wO3jFDce1G6PVyxh/jUV5hM8RijgqxEpISOE+aCz3r2g8IVTrOPx+FFGnR53F6ofdtzabcSsAyZowZnb/FWx3iE6FpCngtl6Fd3Yn4l5qaw==
    username: AgCvFJX5oVhzxonkwrOaJ7CKK5r99eCWf1EWr2Fo+xkIyV9vSrYU+FB7VD0XxK1IyKFGZz0JuG0MvJDCoRJFdKPWKqZwQyhd3yfxYSchXOHtGt4m8eLCGiYYjAAu9l6EwC1hHfQ+LYcKjTZJn53FiNw9LGVBKFjGRkdZse2lYyMQgtv7IFClilWACgX4Qeo2XWfrUpQUfd/uTNhWRnDvt/uZRlOzWf1Xl3Av6UzFLUXZG2SWkZqWHSbhwnbpM13eGJkz4PfmBhODQeC+WY9Bf0eg+ujFzgvo65l0QJuutUiXeZgT2PJjYzt/c9Gcn3d2+EzRoPrh0bPMUvtMhONYPTwwqyPvLqnanE6NHKEfQFC9jEBcREbCFAwN4AsAo9cgIoD4iWIwzr7pezmNDR1I65dNK1axewpZanilm1shwz+yfZ9sS/rkTeMhTwA6flwRruqezCHBWy+k7Xh5ao9MQbTQHknwFcRubLwxPhZE16LX/Df91sLki+910iUZnuk9GgIZaYvUyEjGBX0N9yeJyInp7Pp5muk5UGRnG18slC7E7fVg0gOjSeck5l2lwiyJEMPHI0MZy9rP75Bz3qyt6k/UkjEzRFUWQes4SsUTKC/cvJ+mTawMXuQ/AnuYZKin3c3DVSY/FdeRlhPvW4fPh5/ZxJYkSvQrO6K7MyVKyhRiSCBpQ2TkEVs1wSHAr8P9/01ldrputA==
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: test-sealed-secrets
    type: Opaque
